# Generated by Django 2.1.3 on 2020-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0002_auto_20200609_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='amount',
            field=models.IntegerField(default=200),
        ),
    ]
