# Generated by Django 2.1.3 on 2020-06-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocol', '0003_site_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='protocol.Site'),
        ),
    ]
